name: bvst
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.33.0
  google_fonts: ^6.2.0
  flame_audio: ^2.11.11
# ... otras dependencias
  supabase_flutter: ^2.0.0
  # Usaremos esta para guardar la sesión del usuario localmente:
  shared_preferences: ^2.0.0
  google_mobile_ads: ^5.0.0
  flutter_stripe: ^10.0.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
